### ISSUE TITLE
[request] CPU package power usage and pkg c states

### ISSUE THREAD

**Issue by makedir** [cyring/CoreFreq#495]
Is there a way to show the package power usage and pkg c states?

**Comment by cyring** [comment]
> Is there a way to show the package power usage

In User Interface:
* Press `W`, Package Power is displayed below Cores Power
* Sensors, shortcut `C`, and Custom views are also displaying that data
* Press `F3` for the Views menu

> and pkg c states?
* In startup screen, press shortcut `%` to toggle Package C-States rather than Core C-States
* You can also switch to the Package view, press shortcut `g`

----

Press `h` or `F1` for help, `F2` or `F3` or `F4` for menus

----

On CLI command line, you are getting the same output as UI view using shortcut letter as the command parameter
* `corefreq-cli -g` for Package C-States;
  optionally add as a second parameter the number of loops

* `corefreq-cli -h` will list all possible parameters

----

* Exporting data in JSON is also possible, including Package data
```
corefreq-cli -j
```
