### ISSUE TITLE
Almalinux 9 (again): error: assignment of read-only member ‘vm_flags’

### ISSUE THREAD

**Issue by fishbonesnl** [cyring/CoreFreq#519]
Hello again,

I downloaded the latest master.zip and tried to compile it on the latest Almalinux 9, starting with a clean install.
I get the follow error message during make:

`~/CoreFreq/build/module/corefreqk.c: In function ‘CoreFreqK_mmap’:`
`~/CoreFreq/build/module/corefreqk.c:23538:23: error: assignment of read-only member ‘vm_flags’
23538 |         vma->vm_flags = VM_READ;
      |                       ^
compilation terminated due to -Wfatal-errors.
`
uname -a
`Linux condor 5.14.0-503.14.1.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Nov 19 21:25:22 EST 2024 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by cyring** [comment]
> Hello again,
> 
> I downloaded the latest master.zip and tried to compile it on the latest Almalinux 9, starting with a clean install. I get the follow error message during make:
> ...

Please pull `master` again to get the fix for "Teal Serval"

![2024-12-19-185450_1280x822_scrot](https://github.com/user-attachments/assets/0f2fa101-a392-4002-b0ae-b00b657ffa80)

"Seofoam Ocelot" non regression test

![2024-12-19-190013_1280x822_scrot](https://github.com/user-attachments/assets/a60e6891-a61e-458f-975e-1146b98b0aa7)

**Comment by fishbonesnl** [comment]
I confirm that it works, thanks :+1:
