### ISSUE TITLE
Maybe Add versions?

### ISSUE THREAD

**Issue by pmav99** [cyring/CoreFreq#96]
I think that adopting a versioning scheme (e.g. https://semver.org/ ) + adding versions as git tags + adding a `--version` cli flag would be a useful addition.

**Comment by cyring** [comment]
Lots of good things into this scheme. Indeed I need to improve versionning and packaging.

Adding a `-v` will definitely be part of next release.

`--version` impacts code, and need a refactoring of the arguments parsing.

Btw, do you mind to post some screenshots, I would like to check how your processor is supported by _CoreFreq_

**Comment by pmav99** [comment]
I added a wiki page: https://github.com/cyring/CoreFreq/wiki/CPU-support

**Comment by cyring** [comment]
Thanks for the Wiki initiative : there are many Processor informations to check for accuracy.

I believe you CPU is ultra low C-State capable: do you see any value against the C10 counter ?

Are the memory timings, geometry and frequency accurately equaled to the Dimm specs (ie BIOS) ?

**Comment by pmav99** [comment]
I added some formatting to the wiki. Please review. If you do need feedback, it would not be a bad idea to ask on the arch forum for data. I think it would also be helpful, if you specified which CLI flags  you actually need.

WRT your question, I don't know! I need to check. Since it is a laptop though, chances are that the BIOS will be severely limited.

**Comment by cyring** [comment]
The addition in the wiki looks very good and well organized. I will definitely add a reference to the "CPU-support" page in the README.md

With a laptop, you may find details using [memtest86](https://github.com/Distrotech/memtest86) or CPU-Z Windows like software.

**Comment by cyring** [comment]
Should it print the version only ?
```
$ corefreq-cli -v
1.39.18
```
That way, the version could be embedded into user script for any purpose.

**Comment by pmav99** [comment]
I think it is just fine.

**Comment by cyring** [comment]
Version released.

**Comment by pmav99** [comment]
Works just fine. Closing the issue

**Comment by cyring** [comment]
Hello,

In the README.md, under the question " The CPU freeze or the System crash " is now added a reference to the CPU support Wiki page.

Thanks again for your contribution.

CyrIng

**Comment by JohnAZoidberg** [comment]
Please also add a tag to git and maybe a GitHub release.
Also a mention in the README about which version we're at would be nice :)

I'll add the outputs of my system to the wiki as soon as I've packaged it.

**Comment by cyring** [comment]
To my taste there are already too much version references in the project: 
* `coretypes.h`: the only one **needed** by the source code
* `dkms.conf` : for a DKMS version consistency
* PKGBUILD in the [`corefreq-git`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=corefreq-git) ArchLinux AUR package
* The GitHub Wiki, see the [footer](https://github.com/cyring/CoreFreq/wiki/Live-CD).

Although I believe adding the version in the README.md is a must, I prefer to free myself from this maintenance and focus on developments.
I therefore chose the ArchLinux package as the only support; because the deb and rpm are time consuming.

I am open to any suggestions that lead indeed to more clarity in reading the current version.

**Comment by pmav99** [comment]
@cyring Not sure if you are interested in adding such dev dependencies, but I have been using [bump2version](https://github.com/c4urself/bump2version) and it works quite nicely

**Comment by cyring** [comment]
Closing the issue.

Feel free to come back for any suggestion
